---
# ReplicaSet
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica
  labels:
    app: my-replica-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-replica-app
  template:
    metadata:
      labels:
        app: my-replica-app
    spec:
      containers:
      - name: my-replica-container
        image: nginx:latest
        ports:
          - containerPort: 80